name: conan-fmilibrary CI Conan

# This workflow is triggered on pushes to the repository.
on: [push, workflow_dispatch]

jobs:
  conan-on-linux:
    name: Conan
    runs-on: ubuntu-latest
    container:
      image: docker.io/gcc:${{ matrix.compiler_version }}-bookworm
    env:
      CONAN_LOGIN_USERNAME_OSP: ${{ secrets.osp_artifactory_usr }}
      CONAN_PASSWORD_OSP: ${{ secrets.osp_artifactory_pwd }}
      CONAN_REVISIONS_ENABLED: 1
      CONAN_NON_INTERACTIVE: 1
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        compiler_version: [14]
        option_shared: ['shared=True', 'shared=False']
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y --no-install-recommends python3-pip
          python3 -m pip install --break-system-packages conan
      - name: Build and upload FMI Library
        run: |
          conan profile detect
          conan remote add osp https://osp.jfrog.io/artifactory/api/conan/conan-local --force
          conan create -s build_type=${{ matrix.build_type }} -s compiler.libcxx=libstdc++11 -o "fmilibrary/*:${{ matrix.option_shared }}" .
          conan upload --confirm --force --remote=osp 'fmilibrary*'

  conan-on-windows:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CONAN_LOGIN_USERNAME_OSP: ${{ secrets.osp_artifactory_usr }}
      CONAN_PASSWORD_OSP: ${{ secrets.osp_artifactory_pwd }}
      CONAN_REVISIONS_ENABLED: 1
      CONAN_NON_INTERACTIVE: True
      CONAN_USER_HOME_SHORT: C:\c
      CONAN_USE_ALWAYS_SHORT_PATHS: 1
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025]
        build_type: [Debug, Release]
        option_shared: ['shared=True', 'shared=False']
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install conan
      - run: conan profile detect
      - run: conan remote add osp https://osp.jfrog.io/artifactory/api/conan/conan-local --force
      - run: conan create -s build_type=${{ matrix.build_type }} -o fmilibrary/*:${{ matrix.option_shared }} .
      - run: conan upload --confirm --force --remote=osp 'fmilibrary*'
